# Generated by Django 3.1.1 on 2020-09-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.CharField(max_length=50)),
                ('Editora', models.CharField(max_length=50)),
                ('Paginas', models.IntegerField()),
                ('Titulo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
