# Generated by Django 3.1.1 on 2020-09-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_livraria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='livro',
        ),
    ]
